import React from 'react';

export const metadata = {
  title: "Terms and Conditions | RealCgpa2Percentage",
  description: "Review the terms and conditions for using RealCgpa2Percentage. Understand our calculator disclaimer, accuracy guidelines, and terms of service.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsAndConditions() {
  return (
    <div className="w-full flex flex-col items-center">
      {/* Hero Section */}
      <section className="w-full min-w-0 py-16 px-4 bg-zinc-950 border-b border-zinc-900 text-center">
        <div className="w-full max-w-4xl mx-auto space-y-4">
          <nav className="text-sm font-semibold text-zinc-500 flex items-center justify-center gap-2 mb-2">
            <a href="/" className="hover:text-indigo-400 transition-colors">Home</a>
            <span>/</span>
            <span className="text-zinc-400">Terms & Conditions</span>
          </nav>
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-white">
            Terms & <span className="text-indigo-400">Conditions</span>
          </h1>
          <p className="text-zinc-400 text-base md:text-lg max-w-xl mx-auto">
            Last Updated: June 9, 2026. Please read these terms carefully before using our tools.
          </p>
        </div>
      </section>

      {/* Main Content Section */}
      <section className="w-full min-w-0 py-16 px-4 bg-zinc-950">
        <div className="w-full max-w-3xl mx-auto space-y-12 text-zinc-300 leading-relaxed">
          
          {/* Legal Disclaimer Box */}
          <div className="p-6 rounded-2xl bg-amber-500/5 border border-amber-500/20 space-y-3">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-amber-500/10 flex items-center justify-center text-amber-400">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <h2 className="text-lg font-bold text-white">Academic Disclaimer</h2>
            </div>
            <p className="text-sm text-zinc-400">
              The calculations, equivalencies, and divisions generated by our tools are computed based on publicly available university grading regulations. While we make every effort to ensure formulas are correct and updated, <strong>the output of this website is for informational purposes only. Official grade sheets and final transcripts issued by your academic institution remain the sole legally binding evaluation.</strong>
            </p>
          </div>

          {/* Section 1: Agreement to Terms */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-white tracking-tight">1. Agreement to Terms</h2>
            <p className="text-sm sm:text-base">
              By accessing or using our website, RealCgpa2Percentage, you agree to be bound by these Terms and Conditions. If you do not agree to all of these terms, please do not access or use the calculators or files provided on this website.
            </p>
          </div>

          {/* Section 2: Use of Calculators */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-white tracking-tight">2. Use of Calculators & Tools</h2>
            <p className="text-sm sm:text-base">
              You are granted a non-exclusive, non-transferable, revocable license to access and use our website strictly in accordance with these terms.
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base text-zinc-400">
              <li>Our tools are free of charge for students, teachers, university counselors, and job recruiters.</li>
              <li>You agree not to use automated scripts, bots, scrapers, or indexers to access the calculator application logic in a manner that degrades service performance for other users.</li>
              <li>You agree not to copy, duplicate, or replicate our website's logic, branding, custom UI components, or layouts for commercial purposes without explicit permission.</li>
            </ul>
          </div>

          {/* Section 3: Intellectual Property */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-white tracking-tight">3. Intellectual Property</h2>
            <p className="text-sm sm:text-base">
              The source code, custom design components, theme templates, logos, text, formulas, layout structure, and programmatic optimization patterns are the intellectual property of RealCgpa2Percentage. All mathematical formulas used are mathematical formulas in the public domain or compiled from public university guidelines, but their integration, styling, and representation are protected by copyright laws.
            </p>
          </div>

          {/* Section 4: Limitation of Liability */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-white tracking-tight">4. Limitation of Liability</h2>
            <p className="text-sm sm:text-base">
              Under no circumstances shall RealCgpa2Percentage, its maintainers, or affiliates be liable for any direct, indirect, incidental, special, or consequential damages (including, but not limited to, recruiter rejection, academic evaluation errors, or delay in university admissions) arising from the use of, or inability to use, our calculator tool or database configurations, even if advised of the possibility of such damages.
            </p>
          </div>

          {/* Section 5: Governing Law */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-white tracking-tight">5. Modifications and Governing Law</h2>
            <p className="text-sm sm:text-base">
              We reserve the right to review and modify these terms at any time. Your continued use of the website following any changes signals your acceptance of the new terms. These terms are governed by and construed in accordance with applicable internet standard laws and intellectual property regulations.
            </p>
          </div>

        </div>
      </section>
    </div>
  );
}
